/**
 * tm-data.js — Base de datos de Máquinas Técnicas por juego.
 * Expone window.PokeAnalyzer.tmData
 *
 * Métodos de obtención:
 *   gym      — Recompensa de gimnasio
 *   gift     — Regalo de NPC
 *   floor    — Encontrado en el suelo / campo
 *   purchase — Compra en tienda
 *   casino   — Premio del casino / sala de juegos
 *   quest    — Misión / evento especial
 */

window.PokeAnalyzer = window.PokeAnalyzer || {};

window.PokeAnalyzer.tmData = {

    METHOD_LABELS: {
        gym:      { icon: '🏆', label: 'Gimnasio' },
        gift:     { icon: '🎁', label: 'Regalo' },
        floor:    { icon: '📍', label: 'Suelo' },
        purchase: { icon: '🛒', label: 'Compra' },
        casino:   { icon: '🎰', label: 'Casino' },
        quest:    { icon: '⭐', label: 'Misión' },
    },

    GAMES: [
        { id: 'rby',     label: 'Rojo / Azul / Amarillo', gen: 1, short: 'RBY' },
        { id: 'gsc',     label: 'Oro / Plata / Cristal',  gen: 2, short: 'GSC' },
        { id: 'emerald', label: 'Esmeralda',              gen: 3, short: 'Esmeralda' },
        { id: 'frlg',    label: 'Rojo Fuego / Verde Hoja',gen: 3, short: 'FR/VH' },
        { id: 'dppt',    label: 'Diamante / Perla / Platino', gen: 4, short: 'DPPt' },
        { id: 'hgss',    label: 'HeartGold / SoulSilver', gen: 4, short: 'HG/SS' },
        { id: 'bw',      label: 'Negro / Blanco',         gen: 5, short: 'BW' },
        { id: 'xy',      label: 'X / Y',                  gen: 6, short: 'XY' },
        { id: 'sm',      label: 'Sol / Luna',             gen: 7, short: 'SM' },
        { id: 'swsh',    label: 'Espada / Escudo',        gen: 8, short: 'SwSh' },
        { id: 'sv',      label: 'Escarlata / Púrpura',    gen: 9, short: 'SV' },
    ],

    // ================================================================
    // GEN 1 — Rojo / Azul / Amarillo
    // ================================================================
    rby: [
        { num: 'MT01', move: 'Megapuño',         type: 'normal',   loc: 'Monte Luna (NPC en la salida)',         method: 'gift' },
        { num: 'MT02', move: 'Viento Cortante',   type: 'normal',   loc: 'Centro Comercial de Azulona (P2)',      method: 'purchase' },
        { num: 'MT03', move: 'Danza Espada',      type: 'normal',   loc: 'Silph S.A. (Planta 7)',                 method: 'floor' },
        { num: 'MT04', move: 'Torbellino',        type: 'normal',   loc: 'Ruta 4 (NPC)',                          method: 'gift' },
        { num: 'MT05', move: 'Megapatada',        type: 'normal',   loc: 'Ruta 4 (NPC junto a Monte Luna)',       method: 'gift' },
        { num: 'MT06', move: 'Tóxico',            type: 'poison',   loc: 'Gimnasio de Fucsia (Koga)',             method: 'gym' },
        { num: 'MT07', move: 'Perforador',        type: 'normal',   loc: 'Sala de Juegos de Azulona (premio)',    method: 'casino' },
        { num: 'MT08', move: 'Golpe Cuerpo',      type: 'normal',   loc: 'S.S. Anne (NPC a bordo)',               method: 'gift' },
        { num: 'MT09', move: 'Derribo',           type: 'normal',   loc: 'Dojo de Azafrán (recompensa)',          method: 'gift' },
        { num: 'MT10', move: 'Doble Filo',        type: 'normal',   loc: 'Sala de Juegos de Azulona (premio)',    method: 'casino' },
        { num: 'MT11', move: 'Rayo Burbuja',      type: 'water',    loc: 'Gimnasio de Celeste (Misty)',           method: 'gym' },
        { num: 'MT12', move: 'Pistola Agua',      type: 'water',    loc: 'Monte Luna (B2F)',                      method: 'floor' },
        { num: 'MT13', move: 'Rayo Hielo',        type: 'ice',      loc: 'Centro Comercial de Azulona (P2)',      method: 'purchase' },
        { num: 'MT14', move: 'Ventisca',          type: 'ice',      loc: 'Mansión Pokémon (Isla Canela)',         method: 'floor' },
        { num: 'MT15', move: 'Hiperrayo',         type: 'normal',   loc: 'Centro Comercial de Azulona (P2)',      method: 'purchase' },
        { num: 'MT16', move: 'Día de Pago',       type: 'normal',   loc: 'Ruta 12 (NPC en la casa)',              method: 'gift' },
        { num: 'MT17', move: 'Sumisión',          type: 'fighting', loc: 'Centro Comercial de Azulona (P2)',      method: 'purchase' },
        { num: 'MT18', move: 'Contraataque',      type: 'fighting', loc: 'Centro Comercial de Azulona (P3)',      method: 'purchase' },
        { num: 'MT19', move: 'Sísmico',           type: 'fighting', loc: 'Ruta 25 (NPC)',                         method: 'gift' },
        { num: 'MT20', move: 'Furia',             type: 'normal',   loc: 'Ruta 15',                               method: 'floor' },
        { num: 'MT21', move: 'Megaagotar',        type: 'grass',    loc: 'Gimnasio de Azulona (Erika)',           method: 'gym' },
        { num: 'MT22', move: 'Rayo Solar',        type: 'grass',    loc: 'Mansión Pokémon (Isla Canela, P1)',     method: 'floor' },
        { num: 'MT23', move: 'Furia Dragón',      type: 'dragon',   loc: 'Sala de Juegos de Azulona (premio)',    method: 'casino' },
        { num: 'MT24', move: 'Rayo',              type: 'electric', loc: 'Gimnasio de Carmín (Lt. Surge)',        method: 'gym' },
        { num: 'MT25', move: 'Trueno',            type: 'electric', loc: 'Central Eléctrica',                     method: 'floor' },
        { num: 'MT26', move: 'Terremoto',         type: 'ground',   loc: 'Silph S.A. (Planta 5)',                 method: 'floor' },
        { num: 'MT27', move: 'Fisura',            type: 'ground',   loc: 'Gimnasio de C. Verde Hoja (Giovanni)',  method: 'gym' },
        { num: 'MT28', move: 'Excavar',           type: 'ground',   loc: 'Celeste (NPC del Team Rocket)',         method: 'gift' },
        { num: 'MT29', move: 'Psíquico',          type: 'psychic',  loc: 'Azafrán (NPC en casa, por 1000₽)',     method: 'gift' },
        { num: 'MT30', move: 'Teletransporte',    type: 'psychic',  loc: 'Ruta 9',                                method: 'floor' },
        { num: 'MT31', move: 'Mimético',          type: 'normal',   loc: 'Azafrán (NPC en la Casa de Mimético)',  method: 'gift' },
        { num: 'MT32', move: 'Doble Equipo',      type: 'normal',   loc: 'Centro Comercial de Azulona (P2)',      method: 'purchase' },
        { num: 'MT33', move: 'Reflejo',           type: 'psychic',  loc: 'Central Eléctrica',                     method: 'floor' },
        { num: 'MT34', move: 'Venganza',          type: 'normal',   loc: 'Gimnasio de Plateada (Brock)',          method: 'gym' },
        { num: 'MT35', move: 'Metrónomo',         type: 'normal',   loc: 'Laboratorio de Isla Canela (NPC)',      method: 'gift' },
        { num: 'MT36', move: 'Autodestrucción',   type: 'normal',   loc: 'Silph S.A. (Planta 2)',                 method: 'floor' },
        { num: 'MT37', move: 'Bomba Huevo',       type: 'normal',   loc: 'Centro Comercial de Azulona (P2)',      method: 'purchase' },
        { num: 'MT38', move: 'Llamarada',         type: 'fire',     loc: 'Gimnasio de Isla Canela (Blaine)',      method: 'gym' },
        { num: 'MT39', move: 'Rapidez',           type: 'normal',   loc: 'Ruta 12 (en el suelo)',                 method: 'floor' },
        { num: 'MT40', move: 'Cabezazo',          type: 'normal',   loc: 'Zona Safari (zona 1)',                  method: 'floor' },
        { num: 'MT41', move: 'Ovocuración',       type: 'normal',   loc: 'Azulona (NPC en azotea)',               method: 'gift' },
        { num: 'MT42', move: 'Comesueños',        type: 'psychic',  loc: 'C. Verde Hoja (NPC junto al centro)',   method: 'gift' },
        { num: 'MT43', move: 'Ataque Aéreo',      type: 'flying',   loc: 'Camino Victoria',                       method: 'floor' },
        { num: 'MT44', move: 'Descanso',          type: 'psychic',  loc: 'S.S. Anne (NPC a bordo)',               method: 'gift' },
        { num: 'MT45', move: 'Onda Trueno',       type: 'electric', loc: 'Ruta 24 (en el suelo)',                 method: 'floor' },
        { num: 'MT46', move: 'Psicoonda',         type: 'psychic',  loc: 'Gimnasio de Azafrán (Sabrina)',         method: 'gym' },
        { num: 'MT47', move: 'Explosión',         type: 'normal',   loc: 'Camino Victoria',                       method: 'floor' },
        { num: 'MT48', move: 'Avalancha',         type: 'rock',     loc: 'Azulona (NPC en la azotea)',            method: 'gift' },
        { num: 'MT49', move: 'Triataque',         type: 'normal',   loc: 'Centro Comercial de Azulona (P2)',      method: 'purchase' },
        { num: 'MT50', move: 'Sustituto',         type: 'normal',   loc: 'Azulona (NPC en la azotea)',            method: 'gift' },
        { num: 'MO01', move: 'Corte',             type: 'normal',   loc: 'S.S. Anne (Capitán)',                   method: 'gift' },
        { num: 'MO02', move: 'Vuelo',             type: 'flying',   loc: 'Ruta 16 (NPC en la casa secreta)',      method: 'gift' },
        { num: 'MO03', move: 'Surf',              type: 'water',    loc: 'Zona Safari (NPC en la casa secreta)',  method: 'gift' },
        { num: 'MO04', move: 'Fuerza',            type: 'normal',   loc: 'Fucsia (Guarda del Zona Safari)',       method: 'gift' },
        { num: 'MO05', move: 'Destello',          type: 'normal',   loc: 'Ruta 2 (NPC en la casa, tras Corte)',   method: 'gift' },
    ],

    // ================================================================
    // GEN 3 — Esmeralda
    // ================================================================
    emerald: [
        { num: 'MT01', move: 'Puño Certero',      type: 'fighting', loc: 'Ruta 115 (norte, necesita Surf)',       method: 'floor' },
        { num: 'MT02', move: 'Garra Dragón',      type: 'dragon',   loc: 'Cueva Meteoro (B1F)',                   method: 'floor' },
        { num: 'MT03', move: 'Hidropulso',        type: 'water',    loc: 'Gimnasio de Calagua (Juan)',            method: 'gym' },
        { num: 'MT04', move: 'Paz Mental',        type: 'psychic',  loc: 'Gimnasio de Algaria (Vito y Leti)',     method: 'gym' },
        { num: 'MT05', move: 'Rugido',            type: 'normal',   loc: 'Ruta 114 (NPC)',                        method: 'gift' },
        { num: 'MT06', move: 'Tóxico',            type: 'poison',   loc: 'Parque Battle Frontier / Tienda Petalia', method: 'purchase' },
        { num: 'MT07', move: 'Granizo',           type: 'ice',      loc: 'Triciclo del Desierto (Ruta 111, tienda)', method: 'purchase' },
        { num: 'MT08', move: 'Corpulencia',       type: 'fighting', loc: 'Gimnasio de Portual (Marcial)',         method: 'gym' },
        { num: 'MT09', move: 'Semilladora',       type: 'grass',    loc: 'Ruta 104 (NPC en la cabaña)',           method: 'gift' },
        { num: 'MT10', move: 'Poder Oculto',      type: 'normal',   loc: 'Villa Raíz / Pueblo Pardal (NPC)',      method: 'gift' },
        { num: 'MT11', move: 'Día Soleado',       type: 'fire',     loc: 'Cueva Ígnea (interior)',                method: 'floor' },
        { num: 'MT12', move: 'Mofa',              type: 'dark',     loc: 'Ruta 110 (Truco el Trovador)',          method: 'gift' },
        { num: 'MT13', move: 'Rayo Hielo',        type: 'ice',      loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT14', move: 'Ventisca',          type: 'ice',      loc: 'Triciclo del Desierto (Ruta 111, tienda)', method: 'purchase' },
        { num: 'MT15', move: 'Hiperrayo',         type: 'normal',   loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT16', move: 'Pantalla de Luz',   type: 'psychic',  loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT17', move: 'Protección',        type: 'normal',   loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT18', move: 'Danza Lluvia',      type: 'water',    loc: 'Triciclo del Desierto (Ruta 111, tienda)', method: 'purchase' },
        { num: 'MT19', move: 'Giga Drenaje',      type: 'grass',    loc: 'Ruta 123 (sur, necesita Corte)',        method: 'floor' },
        { num: 'MT20', move: 'Velo Sagrado',      type: 'normal',   loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT21', move: 'Frustración',       type: 'normal',   loc: 'Pueblo Pardal (NPC)',                   method: 'gift' },
        { num: 'MT22', move: 'Rayo Solar',        type: 'grass',    loc: 'Zona Safari (extensión)',               method: 'floor' },
        { num: 'MT23', move: 'Cola Férrea',       type: 'steel',    loc: 'Cueva Meteoro (B2F)',                   method: 'floor' },
        { num: 'MT24', move: 'Rayo',              type: 'electric', loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT25', move: 'Trueno',            type: 'electric', loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT26', move: 'Terremoto',         type: 'ground',   loc: 'Cueva Maremoto (interior profundo)',    method: 'floor' },
        { num: 'MT27', move: 'Retribución',       type: 'normal',   loc: 'Pueblo Pardal (NPC de felicidad)',      method: 'gift' },
        { num: 'MT28', move: 'Excavar',           type: 'ground',   loc: 'Ruta 114 (NPC Buscafósiles)',           method: 'gift' },
        { num: 'MT29', move: 'Psíquico',          type: 'psychic',  loc: 'Camino Victoria (B1F)',                 method: 'floor' },
        { num: 'MT30', move: 'Bola Sombra',       type: 'ghost',    loc: 'Ruta 121 (Centro Comercial Portual)',   method: 'purchase' },
        { num: 'MT31', move: 'Demolición',        type: 'fighting', loc: 'Cueva Granito (1F)',                    method: 'floor' },
        { num: 'MT32', move: 'Doble Equipo',      type: 'normal',   loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT33', move: 'Reflejo',           type: 'psychic',  loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT34', move: 'Onda de Choque',    type: 'electric', loc: 'Gimnasio de Malvalona (Erico)',         method: 'gym' },
        { num: 'MT35', move: 'Lanzallamas',       type: 'fire',     loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT36', move: 'Bomba Lodo',        type: 'poison',   loc: 'Desierto (Ruta 111)',                   method: 'floor' },
        { num: 'MT37', move: 'Tormenta de Arena', type: 'rock',     loc: 'Desierto (Ruta 111, centro)',           method: 'floor' },
        { num: 'MT38', move: 'Llamarada',         type: 'fire',     loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT39', move: 'Tumba Rocas',       type: 'rock',     loc: 'Gimnasio de Férrica (Petra)',           method: 'gym' },
        { num: 'MT40', move: 'Golpe Aéreo',       type: 'flying',   loc: 'Gimnasio de Arborada (Alana)',          method: 'gym' },
        { num: 'MT41', move: 'Tormento',          type: 'dark',     loc: 'Ruta 113 (NPC en la casa)',             method: 'gift' },
        { num: 'MT42', move: 'Fachada',           type: 'normal',   loc: 'Gimnasio de Petalia (Norman)',          method: 'gym' },
        { num: 'MT43', move: 'Poder Secreto',     type: 'normal',   loc: 'Ruta 111 (NPC junto al árbol)',         method: 'gift' },
        { num: 'MT44', move: 'Descanso',          type: 'psychic',  loc: 'Ruta 113 (NPC en la cabaña)',           method: 'gift' },
        { num: 'MT45', move: 'Atracción',         type: 'normal',   loc: 'Ruta 117 (NPC)',                        method: 'gift' },
        { num: 'MT46', move: 'Ladrón',            type: 'dark',     loc: 'Ciudad Calagua (NPC)',                  method: 'gift' },
        { num: 'MT47', move: 'Ala de Acero',      type: 'steel',    loc: 'Centro Comercial de Malvalona (P3)',    method: 'purchase' },
        { num: 'MT48', move: 'Intercambio',       type: 'psychic',  loc: 'Monte Pírico (interior)',               method: 'floor' },
        { num: 'MT49', move: 'Arrebato',          type: 'dark',     loc: 'S.S. Tidal (NPC a bordo)',              method: 'gift' },
        { num: 'MT50', move: 'Sofoco',            type: 'fire',     loc: 'Gimnasio de Candente (Candela)',        method: 'gym' },
        { num: 'MO01', move: 'Corte',             type: 'normal',   loc: 'Férrica (NPC en la casa del Cortador)', method: 'gift' },
        { num: 'MO02', move: 'Vuelo',             type: 'flying',   loc: 'Ruta 119 (tras vencer al rival)',       method: 'gift' },
        { num: 'MO03', move: 'Surf',              type: 'water',    loc: 'Casa de Acromo (Ruta 118)',             method: 'gift' },
        { num: 'MO04', move: 'Fuerza',            type: 'normal',   loc: 'Cueva Granito (NPC con gafas de Excavar)', method: 'gift' },
        { num: 'MO05', move: 'Destello',          type: 'normal',   loc: 'Cueva Granito (NPC en la entrada)',     method: 'gift' },
        { num: 'MO06', move: 'Machada',           type: 'fighting', loc: 'Portual (NPC junto a la cueva)',        method: 'gift' },
        { num: 'MO07', move: 'Cascada',           type: 'water',    loc: 'Cueva Ígnea (NPC)',                     method: 'gift' },
        { num: 'MO08', move: 'Buceo',             type: 'water',    loc: 'Algaria (NPC en la orilla)',            method: 'gift' },
    ],
};
